# ========================================================
# 1. CONFIGURACIÓN DE CONEXIÓN A MYSQL (ENTORNO LOCAL)
# ========================================================
# Apunta a tu propia computadora (localhost) en el puerto 3306
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria_mejia_final?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true

# Tu usuario por defecto de MySQL local
spring.datasource.username=root

# Coloca aquí la contraseña de tu base de datos local (déjalo vacío si usas XAMPP)
spring.datasource.password=

# Driver nativo de comunicación de MySQL para Java
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================================
# 2. CONFIGURACIÓN DE JPA / HIBERNATE
# ========================================================
# El dialecto le dice a Hibernate cómo escribir código SQL optimizado para MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 'update' lee tus clases @Entity y crea/actualiza las tablas sin borrar tus datos de prueba.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Spring Boot todas las consultas JPQL/SQL reales 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================================
# 3. CONFIGURACIÓN ADICIONAL DE SPRING
# ========================================================
# Habilita el refresco de las plantillas HTML de Thymeleaf sin reiniciar el servidor
spring.thymeleaf.cache=false