# ========================================================
# 1. CONFIGURACIÓN DE CONEXIÓN A MYSQL
# ========================================================
# Cambia 'localhost:3306' si tu puerto de MySQL es diferente (ej: 3307)
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria_mejia_final?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true

# Tu usuario por defecto de MySQL (usualmente es root)
spring.datasource.username=root

# Coloca aquí la contraseña real de TU base de datos local de MySQL
spring.datasource.password=

# Driver nativo de comunicación de MySQL para Java
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================================
# 2. CONFIGURACIÓN DE JPA / HIBERNATE
# ========================================================
# El dialecto le dice a Hibernate cómo escribir código SQL optimizado para MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 'update' es la mejor opción para desarrollo: lee tus clases @Entity 
# y crea las tablas que falten en tu base de datos sin borrar tus datos de prueba.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Spring Boot todas las consultas JPQL/SQL reales 
# que se ejecutan. Te servirá muchísimo para tu sustentación y debugging.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================================
# 3. CONFIGURACIÓN ADICIONAL DE SPRING
# ========================================================
# Habilita el refresco de las plantillas HTML de Thymeleaf sin reiniciar el servidor entero
spring.thymeleaf.cache=false